name: Parallel-Workflow
 
on:
  push:
    branches:
      - main
 
env:
  AWS_REGION: ap-south-1
permissions:
    id-token: write
    contents: read  
 
jobs:
  #Continuous-Integration:  
 
  job1:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          tflint -f compact | tee report-tflint.txt
        continue-on-error: true
  job2:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: CheckOV
        run: |
          sudo apt-get install -y python3-pip
          pip install checkov
          export PATH=$PATH:/home/ubuntu/.local/bin
          checkov --directory ./ --skip-check CKV_AWS_130,CKV_AWS_230,CKV_AWS_229,CKV_AWS_232,CKV_AWS_231,CKV_AWS_12,CKV_AWS_11,CKV_AWS_1,CKV_AWS_18,CKV_AWS_144,CKV2_AWS_11,CKV2_AWS_1,CKV2_AWS_12,CKV2_AWS_6,CKV_AWS_19,CKV_AWS_145,CKV_AWS_21 | tee report-checkov.txt
        continue-on-error: true
  job3:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
        role-to-assume: arn:aws:iam::061051245586:oidc-provider/github.kyndryl.net/_services/token #change to reflect your IAM role’s ARN
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}  
 
      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color      
 
